Repository SoichiroYamane/sketchybar-app-font-bg, pull requests merged in 2024-12, with the labels that each got.

#7 fix: mapping of devonthink 🐛
  mappings/:devonthink:
Labels: bug

#8 fix: mapping of Ableton Live 🐛
  mappings/:ableton_live:
Labels: bug

#9 :feat add 9 icons ✨
  mappings/:maps:
  mappings/:music:
  mappings/:notes:
  mappings/:notion_calendar:
  mappings/:numbers:
  mappings/:photos:
  mappings/:podcasts:
  mappings/:texshop:
  mappings/:xquartz:
  public/dist/icon_map.json
  public/dist/icon_map.lua
  public/dist/icon_map.sh
  public/dist/react/Maps.d.ts
  public/dist/react/Maps.js
  public/dist/react/Music.d.ts
  public/dist/react/Music.js
  public/dist/react/Notes.d.ts
  public/dist/react/Notes.js
  public/dist/react/NotionCalendar.d.ts
  public/dist/react/NotionCalendar.js
  public/dist/react/Numbers.d.ts
  public/dist/react/Numbers.js
  public/dist/react/Photos.d.ts
  public/dist/react/Photos.js
  public/dist/react/Podcasts.d.ts
  public/dist/react/Podcasts.js
  public/dist/react/Texshop.d.ts
  public/dist/react/Texshop.js
  public/dist/react/Xquartz.d.ts
  public/dist/react/Xquartz.js
  public/dist/react/index.d.ts
  public/dist/react/index.js
  public/dist/sketchybar-app-font-bg.eot
  public/dist/sketchybar-app-font-bg.json
  public/dist/sketchybar-app-font-bg.svg
  public/dist/sketchybar-app-font-bg.symbol.svg
  public/dist/sketchybar-app-font-bg.ttf
  public/dist/sketchybar-app-font-bg.woff
  public/dist/sketchybar-app-font-bg.woff2
  svgs/:maps:.svg
  svgs/:music:.svg
  svgs/:notes:.svg
  svgs/:notion_calendar:.svg
  svgs/:numbers:.svg
  svgs/:photos:.svg
  svgs/:podcasts:.svg
  svgs/:texshop:.svg
  svgs/:xquartz:.svg
Labels: feature, icon

#12 icon: add cursor, claude, pixelmator ⚛️ #11
  .gitignore
  mappings/:claude:
  mappings/:cursor:
  mappings/:pixelmator:
  svgs/:claude:.svg
  svgs/:cursor:.svg
  svgs/:pixelmator:.svg
Labels: icon

#13 Add Pixelmator Pro as alias of Pixelmator
  mappings/:pixelmator:
Labels: icon

#14 feat: 🎸 add ghostty and zoom
  mappings/:ghostty2:
  mappings/:zoom:
  public/dist/icon_map.json
  public/dist/icon_map.lua
  public/dist/icon_map.sh
  public/dist/react/index.d.ts
  public/dist/react/index.js
  public/dist/sketchybar-app-font-bg.eot
  public/dist/sketchybar-app-font-bg.json
  public/dist/sketchybar-app-font-bg.svg
  public/dist/sketchybar-app-font-bg.symbol.svg
  public/dist/sketchybar-app-font-bg.ttf
  public/dist/sketchybar-app-font-bg.woff
  public/dist/sketchybar-app-font-bg.woff2
  svgs/:ghostty2:.svg
  svgs/:ghostty:.svg
  svgs/:zoom:.svg
Labels: icon
